--- #YAML:1.0
name:                Log-Dispatch-Config-TestLog
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Log::Dispatch::Binlog:         0
    Log::Dispatch::Config:         0
    Path::Class:                   0
    Sub::Override:                 0
    Test::Builder:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
